name: "Post to Bluesky (Automatic In-Season Mode)"
on:
  schedule:
    - cron: "*/15 9-23 * 3-9 *" # runs only 9-23 UTC-4/UTC-5 (EDT/EST) with an 9 hour break in order to save actions quota, can be interchangable between 15 and 30 minute intervals
      timezone: "America/New_York"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      # - run: npm install axios
      # - run: npm install tsl-mastodon-api
      - run: npm ci
      - run: npm run build
      - name: Send post
        run: npm start
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
