name: "Post to Bluesky (Automatic In-Season Mode)"
on:
  repository_dispatch: # the cron job uses the same cron operand used below (time relative to America/New_York), but uses cron-job.org to trigger the workflow through the API instead of github's own cron scheduler
  # reason why I moved it to cron-job.org because github's own scheduler was too slow and out of sync from the scheduled run time, it's not going to be effective at what I want to do
  # the cron used for this workflow is: "*/15 13-23,0-3 * 3-9 *" --- it runs every 15 minutes relative to the top of the hour between 13-23 & 0-3 UTC (or 9-23 ET in America/New_York terms) at any given (all seven) day between march through september
    types: [run-cron-job]
jobs:
  build:
    runs-on: self-hosted # the action goes to my homelab machines so it doesn't use github's because I don't want to spend money
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm install axios
      - run: npm install tsl-mastodon-api
      - run: npm ci
      - run: npm run build
      - name: Send post
        run: npm start
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
