name: "Post to Bluesky (Automatic In-Season Mode)"
on:
  repository_dispatch: # the dispatch will be called from an external cron scheduler over at cron-job.org to trigger the workflow through the API instead of github's own cron scheduler
  # reason why I use that instead of github's own cron scheduler is because it was too slow and out of sync from the scheduled run time, it's not going to be effective at what I want to do (see https://github.com/k1yrix/tigers-auto-mirror/actions/workflows/post-auto.yml with the amount of insane delay compared to running through the external scheduler)
  # the cron used for this workflow is: "*/15 13-23,0-3 * 3-9 *" --- it runs every 15 minutes relative to the top of the hour between 13-23 & 0-3 UTC (or 9-23 ET in America/New_York terms) at any given (all seven) day between march through september
  # there is a 9 hour gap between 3-13 (or 0-9 ET in America/New_York terms) to possibly reset API rate limits and also because it's not good to keep this up and running 24/7 during down time
    types: [run-cron-job]
jobs:
  build:
    # runs-on: self-hosted # the action goes to my homelab machines so it doesn't use github's because I don't want to spend money
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm install axios
      - run: npm install tsl-mastodon-api
      - run: npm ci
      - run: npm run build
      - name: Send post
        run: npm start
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
